name: LobbyFly
version: 1.5.2
main: me.crazybanana4life.lobbyfly.LobbyFly
api-version: 1.16
authors: [CrazyBanana]
description: This is a plugin where people with the permission have the ability to "/fly" in the lobby!
commands:
  fly:
    description: Use this command to enable/disable fly in your lobby!
  lfreload:
    description: Use this command to reload the plugin